### ISSUE TITLE
支付签名问题

### ISSUE THREAD

**Issue by nilmeme** [cuter44/wxpay-sdk#10]
获取得到prepay_id再签名后，回送给移动端的时候签名不对，不能进行支付

**Comment by cuter44** [comment]
经过检查, 功能在 0.6.4.0-dev c68eb9e611ca66c459cab258e097396bd349f0e4 中工作正常.  

以下是可以参考的建议:
1. 检查配置文件等参数来源是否已正确配置
2. `src/com/.../wxpay/servlet/JSAPISigner.java#76` 提供了关于此功能的代码片段, 可以作为参考.

感谢您使用 wxpay-sdk
