### ISSUE TITLE
这个项目有集成微信企业支付吗？

### ISSUE THREAD

**Issue by nilmeme** [cuter44/wxpay-sdk#11]

**Comment by cuter44** [comment]
企业支付即微信支付+userid→openid转换接口. (参见 http://qydev.weixin.qq.com/wiki/index.php?title=%E5%BE%AE%E4%BF%A1%E6%94%AF%E4%BB%98)

到当前版本 0.6.4.0-dev 07dc2301d8d172e2c3ae9177e91313d2522d2fb4 为止:
微信支付的主要接口已覆盖(在 wxpay 中).
userid→openid转换接口已覆盖(在 wxcp 中).

软件包的完成度现已可以在 [Featured APIs](https://github.com/cuter44/wxpay-sdk/wiki/%5BCN%5DFeatured-APIs) 查阅. (不过很抱歉 wiki 本身也正在施工中)

感谢您投递此 ISSUE.
