### ISSUE TITLE
Load identification failed

### ISSUE THREAD

**Issue by zhangruilong** [cuter44/wxpay-sdk#14]
Can't found file ".p12"

**Comment by cuter44** [comment]
Sorry to keep you waiting, I didn't receive a mail notification.

The `apiclient_cert.p12` is the certificate that you acquire from weixin's authorication while your application to wechat-pay(微信支付) service admitted. Which can be downloaded from https://pay.wx.qq.com/ . You should get a file named `cert.zip`, in which there is the certificate. Put this file into your classpath so the application can reach it.

**If your public/service account is not authorized to use this service**, please find your `wxpay.properties` and quote the following line:

```
LOAD_IDENTIFICATION=/apiclient_cert.p12
```

to:

```
#LOAD_IDENTIFICATION=/apiclient_cert.p12
```

so you can skip loading it.

As you guessed, you can also change this line to something else to adjust your classpath.

Thank you for your choise of wxpay-sdk. ฅ(・ω・ฅ)

**Comment by zhangruilong** [comment]
谢谢你的付出，我明白了
